# 1. Introduction

This chapte outlines techniques for effectively loading, storing, and manipulating in-memory data in Python. The topic is very broad: datasets can come from a wide range of sources and a wide range of formats, including be collections of documents, collections of images, collections of sound clips, collections of numerical measurements, or nearly anything else. Despite this apparent heterogeneity, it will help us to think of all data fundamentally as arrays of numbers.

For example, images–particularly digital images–can be thought of as simply two-dimensional arrays of numbers representing pixel brightness across the area. Sound clips can be thought of as one-dimensional arrays of intensity versus time. Text can be converted in various ways into numerical representations, perhaps binary digits representing the frequency of certain words or pairs of words. No matter what the data are, the first step in making it analyzable will be to transform them into arrays of numbers. (We will discuss some specific examples of this process later in Feature Engineering)

For this reason, efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing data science. We'll now take a look at the specialized tools that Python has for handling such numerical arrays: the `NumPy` package, and the `Pandas` package (discussed in Chapter 3).

`NumPy` is the fundamental package for scientific computing with Python. It contains among other things:

  + a powerful N-dimensional array object
  + sophisticated (broadcasting) functions
  + tools for integrating C/C++ and Fortran code
  + useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, `NumPy` can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

This chapter will cover `NumPy` in detail. `NumPy` (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers. In some ways, NumPy arrays are like Python's built-in list type, but `NumPy` arrays provide much more efficient storage and data operations as the arrays grow larger in size. NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect of data science interests you.

If you followed the advice outlined in the Preface and installed the Anaconda stack, you already have `NumPy` installed and ready to go. If you're more the do-it-yourself type, you can go to this [link](http://www.numpy.org/)  and follow the installation instructions found there. Once you do, you can import `NumPy` and double-check the version:

In [ ]:
import numpy
numpy.__version__

'1.17.4'

For the pieces of the package discussed here, I'd recommend NumPy version 1.8 or later. By convention, you'll find that most people in the SciPy/PyData world will import `NumPy` using np as an alias:

In [ ]:
import numpy as np

Throughout this chapter, and indeed the rest of the book, you'll find that this is the way we will import and use NumPy. You can also visit official site for numpy at this [link](http://www.numpy.org)

# 2. Basics of Numpy

NumPy’s main object is the homogeneous multidimensional array.

 1. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
 2. In NumPy dimensions are called axes. The number of axes is rank.
 3. NumPy’s array class is called ndarray. It is also known by the alias array.
 
While Python's array object provides efficient storage of array-based data, NumPy adds to this efficient operations on that data. We will explore these operations in later sections; here we'll demonstrate several ways of creating a NumPy array.

We'll start with the standard NumPy import, under the alias np:

In [ ]:
import numpy as np

## 2.1 Creating Numpy Arrary

### 2.1.1 From Python list

First, we can use **`np.array`** to create arrays from Python lists or tuples:

In [ ]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

If we want to explicitly set the data type of the resulting array, we can use the  **`dtype`** keyword:

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Finally, unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:

In [ ]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### 2.1.2 From Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

 + Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.
For example: **`np.zeros`**, **`np.ones`**, **`np.full`**, **`np.empty`**, etc.

 + To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
     + **`np.arrange`**: returns evenly spaced values within a given interval after step size is specified.
     + **`np.linspace`**: returns evenly spaced values within a given interval after num no. of elements are specified.
     
 + To create sequences of random numbers, NumPy uses below function
     + **`np.random.random`**: Create an array of uniformly distributed for given shape. Values lies between 0 and 1.
     + **`np.random.normal`**: Create an array of normally distributed random values for given shape. 
     + **`np.random.randint`**: Create a array of random integers in the iven interval.
       
  + Some Specialised array function
     + **`np.eye`**: Create an identity matrix
     + **`np.empty`**: Create an uninitialized array. The values will be whatever happens to already exist at that memory location
     

In [ ]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.71708348,  0.16865909, -1.94341254],
       [-0.1619349 ,  0.0364987 ,  1.48820375],
       [ 0.20987276, -0.74707054,  0.45024452]])

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 6, 9],
       [1, 8, 8],
       [6, 2, 2]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

## 2.2 Standard Data Types in NumPy

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table. Note that when constructing an array, they can be specified using a string or using the associated NumPy object.

In [ ]:
np.zeros(10, dtype='int16')
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

|Data type         |	Description                                                                              |
|-----------------------|-------------------------------------------------------------------------------------------|
|bool_	|Boolean (True or False) stored as a byte|
|int_	|Default integer type (same as C long; normally either int64 or int32)|
|intc	|Identical to C int (normally int32 or int64)|
|intp	|Integer used for indexing (same as C ssize_t; normally either int32 or int64)|
|int8	|Byte (-128 to 127)|
|int16	|Integer (-32768 to 32767)|
|int32	|Integer (-2147483648 to 2147483647)|
|int64	|Integer (-9223372036854775808 to 9223372036854775807)|
|uint8	|Unsigned integer (0 to 255)|
|uint16	|Unsigned integer (0 to 65535)|
|uint32	|Unsigned integer (0 to 4294967295)|
|uint64	|Unsigned integer (0 to 18446744073709551615)|
|float_	|Shorthand for float64.|
|float16	|Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
|float32	|Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
|float64	|Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
|complex_	|Shorthand for complex128.|
|complex64	|Complex number, represented by two 32-bit floats|
|complex128	|Complex number, represented by two 64-bit floats|

More advanced type specification is possible, such as specifying big or little endian numbers along with NumPy compound data types.

# 3. Data Manipulation

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer packages like Pandas (Chapter 3) are built around the NumPy array. This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays. 

We'll cover a few categories of basic array manipulations here:

 + Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
 + Indexing of arrays: Getting and setting the value of individual array elements
 + Slicing of arrays: Getting and setting smaller subarrays within a larger array
 + Reshaping of arrays: Changing the shape of a given array
 + Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many



## 3.1 Attributes of arrays

We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has below attributes which can be accessed by calling below syntax: 

> (arrayname).(attribute)


 + ndim : the number of dimensions
 + shape : the size of each dimension
 + size : the total size of the array
 + dtype: the data type of the array
 + itemsize: lists the size (in bytes) of each array element
 + nbytes: lists the total size (in bytes) of the array
 
 In general, we expect that nbytes is equal to itemsize times size.

In [ ]:
print("number of dimensions of x3: ", x3.ndim)
print("size of each dimension of x3:", x3.shape)
print("total size of x3: ", x3.size)
print("data type of x3:", x3.dtype)
print("size (in bytes) of each element of x3:", x3.itemsize, "bytes")
print("total size (in bytes) of x3:", x3.nbytes, "bytes")

number of dimensions of x3:  3
size of each dimension of x3: (3, 4, 5)
total size of x3:  60
data type of x3: int64
size (in bytes) of each element of x3: 8 bytes
total size (in bytes) of x3: 480 bytes


## 3.2 Indexing of arrays

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, the ith value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists. We can also index from the end of the array, for which we can use negative indices. Here, we have to remember that negative index starts from -1.

> Numpy Array index starts from 0 in normal order and with -1 in reverse order.

In [ ]:
print(x1)
print(x1[0])
print(x1[5])
print(x1[-1])
print(x1[-5])

[5 0 3 3 7 9]
5
9
9
0


In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [ ]:
print(x2)
print(x2[0,0])
print(x2[1,3])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
8


In [ ]:
print(x3)
print(x3[0,0,0])
print(x3[2,1,3])

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
8
3


Values can also be modified using any of the above index notation. Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [ ]:
x2[0, 0] = 12
print(x2)

x1[0] = 3.14159  # this will be truncated!
print(x1)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[3 0 3 3 7 9]


## 3.3 Slicing of arrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon **`(:)`** character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array **`x`**, use this:

> x[start:stop:step]

If any of these are unspecified, they default to the values **`start=0`**, **`stop=size of dimension`**,  **`step=1`**. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.



### 3.3.1 One-dimensional array

In [ ]:
print(x1)
print(x1[:5])  # first five elements
print(x1[5:])  # elements after index 5
print(x1[2:5])  # middle sub-array
print(x1[::2])  # every other element
print(x1[1::2])  # every other element, starting at index 1

[3 0 3 3 7 9]
[3 0 3 3 7]
[9]
[3 3 7]
[3 3 7]
[0 3 9]


A potentially confusing case is when the **`step`** value is negative. In this case, the defaults for **`start`** and **`stop`** are swapped. This becomes a convenient way to reverse an array:

In [ ]:
print(x1[::-1])  # all elements, reversed
print(x1[5::-2]) # reversed every other from index 5

[9 7 3 3 0 3]
[9 3 0]


### 3.3.2 Multi-dimensional arrary

Multi-dimensional slices work in the same way, with multiple slices separated by commas. For example:

In [ ]:
print(x2)
print(x2[:2, :3])  # two rows, three columns
print(x2[:3, ::2])  # all rows, every other column
print(x2[::-1, ::-1]) # subarray dimensions can even be reversed together:

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  5  2]
 [ 7  6  8]]
[[12  2]
 [ 7  8]
 [ 1  7]]
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


### 3.3.3 Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon **`(:)`**:

In [ ]:
print(x2[:, 0])  # first column of x2
print(x2[0, :])  # first row of x2
print(x2[0])  # equivalent to x2[0, :]

[12  7  1]
[12  5  2  4]
[12  5  2  4]


## 3.4 Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [ ]:
print(x2)
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5]
 [7 6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)
print(x2)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

## 3.5 Creating copies of arrays
Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the **`copy()`** method:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## 3.6 Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid, you can do the following:

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. This can be done with the reshape method, or more easily done by making use of the **`newaxis`** keyword within a slice operation:

In [ ]:
x = np.array([1, 2, 3])

# row vector via reshape
print(x.reshape((1, 3)))

# row vector via newaxis
print(x[np.newaxis, :])

# column vector via reshape
print(x.reshape((3, 1)))

# column vector via newaxis
print(x[:, np.newaxis])

[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


## 3.7 Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### 3.7.1 Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines **`np.concatenate`**, **`np.vstack`**, and **`np.hstack`**.  **`np.concatenate`** takes a tuple or list of arrays as its first argument, as we can see below. We can also concatenate more than two arrays at once. It can also be used for two-dimensional arrays.

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))

z = [99, 99, 99]
print(np.concatenate([x, y, z]))

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along the first axis
print(np.concatenate([grid, grid]))

# concatenate along the second axis (zero-indexed)
print(np.concatenate([grid, grid], axis=1))

[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


For working with arrays of mixed dimensions, it can be clearer to use the **`np.vstack`** (vertical stack) and **`np.hstack`** (horizontal stack) functions. Similary, **`np.dstack`** will stack arrays along the third axis.

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
print(np.vstack([x, grid]))

# horizontally stack the arrays
y = np.array([[99],
              [99]])
print(np.hstack([grid, y]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[ 9  8  7 99]
 [ 6  5  4 99]]


### 3.7.2 Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions **`np.split`**, **`np.hsplit`**, and **`np.vsplit`**. For each of these, we can pass a list of indices giving the split points. Notice that N split-points, leads to N + 1 subarrays. The related functions **`np.hsplit`** and **`np.vsplit`** are similar. Similarly, **`np.dsplit`** will split arrays along the third axis.

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

grid = np.arange(16).reshape((4, 4))
print(grid)

upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

left, right = np.hsplit(grid, [2])
print(left)
print(right)

[1 2 3] [99 99] [3 2 1]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# 4.  Computation on NumPy array

Up until now, we have been discussing some of the basic nuts and bolts of NumPy; in the next few sections, we will dive into the reasons that NumPy is so important in the Python data science world. Namely, it provides an easy and flexible interface to optimized computation with arrays of data.

Let's look at how we can speed up our calculation using NumPy arrary.

## 4.1 Universal functions

Computation on NumPy arrays can be very fast, or it can be very slow. The key to making it fast is to use vectorized operations, generally implemented through NumPy's **universal functions (ufuncs)**. 

### 4.1.1 Available ufuncs

There are currently more than 60 universal functions defined in **numpy** on one or more types, covering a wide variety of operations. 

#### 4.1.1.1 Math operations
---
Below is the list of math operations functions available in numpy.

|ufunc|Description|Minimum no. of inputs|
|----------|--------------|--------------------------------------|
|np.negative(x, /[, out, where, casting, order, …])|Numerical negative, element-wise.|1|
|np.positive(x, /[, out, where, casting, order, …])|Numerical positive, element-wise.|1|
|np.absolute(x, /[, out, where, casting, order, …])|Calculate the absolute value element-wise.|1|
|np.fabs(x, /[, out, where, casting, order, …])|Compute the absolute values element-wise.|1|
|np.rint(x, /[, out, where, casting, order, …])|Round elements of the array to the nearest integer.|1|
|np.sign(x, /[, out, where, casting, order, …])|Returns an element-wise indication of the sign of a number.|1|
|np.conj(x, /[, out, where, casting, order, …])|Return the complex conjugate, element-wise.|1|
|np.exp(x, /[, out, where, casting, order, …])|Calculate the exponential of all elements in the input array.|1|
|np.exp2(x, /[, out, where, casting, order, …])|Calculate 2**p for all p in the input array.|1|
|np.log(x, /[, out, where, casting, order, …])|Natural logarithm, element-wise.|1|
|np.log2(x, /[, out, where, casting, order, …])|Base-2 logarithm of x.|1|
|np.log10(x, /[, out, where, casting, order, …])|Return the base 10 logarithm of the input array, element-wise.|1|
|np.expm1(x, /[, out, where, casting, order, …])|Calculate exp(x) - 1 for all elements in the array.|1|
|np.log1p(x, /[, out, where, casting, order, …])|Return the natural logarithm of one plus the input array, element-wise.|1|
|np.sqrt(x, /[, out, where, casting, order, …])|Return the non-negative square-root of an array, element-wise.|1|
|np.square(x, /[, out, where, casting, order, …])|Return the element-wise square of the input.|1|
|np.cbrt(x, /[, out, where, casting, order, …])|Return the cube-root of an array, element-wise.|1|
|np.reciprocal(x, /[, out, where, casting, …])|Return the reciprocal of the argument, element-wise.|1|
|np.add(x1, x2, /[, out, where, casting, order, …])|Add arguments element-wise.|2|
|np.subtract(x1, x2, /[, out, where, casting, …])|Subtract arguments, element-wise.|2|
|np.multiply(x1, x2, /[, out, where, casting, …])|Multiply arguments element-wise.|2|
|np.divide(x1, x2, /[, out, where, casting, …])|Returns a true division of the inputs, element-wise.|2|
|np.logaddexp(x1, x2, /[, out, where, casting, …])|Logarithm of the sum of exponentiations of the inputs.|2|
|np.logaddexp2(x1, x2, /[, out, where, casting, …])|Logarithm of the sum of exponentiations of the inputs in base-2.|2|
|np.true_divide(x1, x2, /[, out, where, …])|Returns a true division of the inputs, element-wise.|2|
|np.floor_divide(x1, x2, /[, out, where, …])|Return the largest integer smaller or equal to the division of the inputs.|2|
|np.power(x1, x2, /[, out, where, casting, …])|First array elements raised to powers from second array, element-wise.|2|
|np.remainder(x1, x2, /[, out, where, casting, …])|Return element-wise remainder of division.|2|
|np.mod(x1, x2, /[, out, where, casting, order, …])|Return element-wise remainder of division.|2|
|np.fmod(x1, x2, /[, out, where, casting, …])|Return the element-wise remainder of division.|2|
|np.divmod(x1, x2[, out1, out2], / [[, out, …])|Return element-wise quotient and remainder simultaneously.|2|
|np.heaviside(x1, x2, /[, out, where, casting, …])|Compute the Heaviside step function.|2|
|np.gcd(x1, x2, /[, out, where, casting, order, …])|Returns the greatest common divisor of |x1| and |x2||2|
|np.lcm(x1, x2, /[, out, where, casting, order, …])|Returns the lowest common multiple of |x1| and |x2||2|


**Tip:**

> The optional output arguments can be used to help you save memory for large calculations. If your arrays are large, complicated expressions can take longer than absolutely necessary due to the creation and (later) destruction of temporary calculation spaces. For example, the expression `G = a * b + c` is equivalent to `t1 = A * B`;` `G = T1 + C`; `del` t1. It will be more quickly executed as `G = A * B`; `add(G, C, G)`` which is the same as `G = A * B`; `G += C`.




In [ ]:
x = np.arange(4)
print("x     =", x)
print("-x=",np.negative(x))
print("+x=",np.positive(x))
print("absolute(x)=",np.absolute(x))
print("fabsolute(x)=",np.fabs(x))
print("round(x)=",np.rint(x))
print("sign(x)=",np.sign(x))
print("complex conjugate(x)=",np.conj(x))
print("exponential(x)=",np.exp(x))
print("2^p(x)=",np.exp2(x))
print("natural log(x)=",np.log(x))
print("fabsolutlog-base 2(x)=",np.log2(x))
print("fabsolutlog-base 10(x)=",np.log10(x))
print("exp(x) - 1(x)=",np.expm1(x))
print("natural logarithm of one plus(x)=",np.log1p(x))
print("non-negative square-root(x)=",np.sqrt(x))
print("square(x)=",np.square(x))
print("cube-root (x)=",np.cbrt(x))
print("reciprocal(x)=",np.reciprocal(x))


x     = [0 1 2 3]
-x= [ 0 -1 -2 -3]
+x= [0 1 2 3]
absolute(x)= [0 1 2 3]
fabsolute(x)= [0. 1. 2. 3.]
round(x)= [0. 1. 2. 3.]
sign(x)= [0 1 1 1]
complex conjugate(x)= [0 1 2 3]
exponential(x)= [ 1.          2.71828183  7.3890561  20.08553692]
2^p(x)= [1. 2. 4. 8.]
natural log(x)= [      -inf 0.         0.69314718 1.09861229]
fabsolutlog-base 2(x)= [     -inf 0.        1.        1.5849625]
fabsolutlog-base 10(x)= [      -inf 0.         0.30103    0.47712125]
exp(x) - 1(x)= [ 0.          1.71828183  6.3890561  19.08553692]
natural logarithm of one plus(x)= [0.         0.69314718 1.09861229 1.38629436]
non-negative square-root(x)= [0.         1.         1.41421356 1.73205081]
square(x)= [0 1 4 9]
cube-root (x)= [0.         1.         1.25992105 1.44224957]
reciprocal(x)= [-9223372036854775808                    1                    0
                    0]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in log
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in log2
  del sys.path[0]
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in log10
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:20: RuntimeWarning: divide by zero encountered in reciprocal
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in reciprocal


In [ ]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", np.add(x, 5))
print("x - 5 =", np.subtract(x, 5))
print("x * 2 =", np.multiply(x, 2))
print("x / 2 =", np.divide(x, 2))
print("log(exp(x1) + exp(x2)) =", np.logaddexp(x, 2))  
print("log2(2**x1 + 2**x2) =", np.logaddexp2(x, 2))  
print("x // 2 =", np.true_divide(x, 2))  # true division
print("x // 2 =", np.floor_divide(x, 2))  # floor division
print("x // 2 =", np.remainder(x, 2))  # floor division
print("x // 2 =", np.divmod(x, 2))  # gives element-wise quotient and remainder simultaneously.
print("x ** 2 = ", np.power(x, 2))
print("x % 2  = ", np.mod(x,  2))
print("GCD=",np.gcd(12, 20)) # Returns the greatest common divisor of |x1| and |x2|
print("LCM =",np.lcm(12,20)) # Returns the lowest common multiple of |x1| and |x2|

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
log(exp(x1) + exp(x2)) = [2.12692801 2.31326169 2.69314718 3.31326169]
log2(2**x1 + 2**x2) = [2.32192809 2.5849625  3.         3.5849625 ]
x // 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x // 2 = [0 1 0 1]
x // 2 = (array([0, 0, 1, 1]), array([0, 1, 0, 1]))
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]
GCD= 4
LCM = 60


#### 4.1.1.2 Trigonometric functions
---
All trigonometric functions use radians when an angle is called for. The ratio of degrees to radians is $180^{\circ}/\pi$.

|ufunc|Description|Minimum no. of array|
|----------|--------------|--------------------------------------|
|np.sin(x, /[, out, where, casting, order, …])|Trigonometric sine, element-wise.|1|
|np.cos(x, /[, out, where, casting, order, …])|Cosine element-wise.|1|
|np.tan(x, /[, out, where, casting, order, …])|Compute tangent element-wise.|1|
|np.arcsin(x, /[, out, where, casting, order, …])|Inverse sine, element-wise.|1|
|np.arccos(x, /[, out, where, casting, order, …])|Trigonometric inverse cosine, element-wise.|1|
|np.arctan(x, /[, out, where, casting, order, …])|Trigonometric inverse tangent, element-wise.|1|
|np.sinh(x, /[, out, where, casting, order, …])|Hyperbolic sine, element-wise.|1|
|np.cosh(x, /[, out, where, casting, order, …])|Hyperbolic cosine, element-wise.|1|
|np.tanh(x, /[, out, where, casting, order, …])|Compute hyperbolic tangent element-wise.|1|
|np.arcsinh(x, /[, out, where, casting, order, …])|Inverse hyperbolic sine element-wise.|1|
|np.arccosh(x, /[, out, where, casting, order, …])|Inverse hyperbolic cosine, element-wise.|1|
|np.arctanh(x, /[, out, where, casting, order, …])|Inverse hyperbolic tangent element-wise.|1|
|np.deg2rad(x, /[, out, where, casting, order, …])|Convert angles from degrees to radians.|1|
|np.rad2deg(x, /[, out, where, casting, order, …])|Convert angles from radians to degrees.|1|
|np.arctan2(x1, x2, /[, out, where, casting, …])|Element-wise arc tangent of x1/x2 choosing the quadrant correctly.|2|
|np.hypot(x1, x2, /[, out, where, casting, …])|Given the “legs” of a right triangle, return its hypotenuse.|2|




In [ ]:

theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


#### 4.1.1.3 Floating functions
---
Recall that all of these functions work element-by-element over an array, returning an array output. The description details only a single operation.

|ufunc|Description|Minimum no. of array|
|----------|--------------------|---------------------|
|np.isfinite(x, /[, out, where, casting, order, …])|Test element-wise for finiteness (not infinity or not Not a Number).|1|
|np.isinf(x, /[, out, where, casting, order, …])|Test element-wise for positive or negative infinity.|1|
|np.isnan(x, /[, out, where, casting, order, …])|Test element-wise for NaN and return result as a boolean array.|1|
|np.isnat(x, /[, out, where, casting, order, …])|Test element-wise for NaT (not a time) and return result as a boolean array.|1|
|np.fabs(x, /[, out, where, casting, order, …])|Compute the absolute values element-wise.|1|
|np.signbit(x, /[, out, where, casting, order, …])|Returns element-wise True where signbit is set (less than zero).|1|
|np.spacing(x, /[, out, where, casting, order, …])|Return the distance between x and the nearest adjacent number.|1|
|np.modf(x[, out1, out2], / [[, out, where, …])|Return the fractional and integral parts of an array, element-wise.|1|
|np.frexp(x[, out1, out2], / [[, out, where, …])|Decompose the elements of x into mantissa and twos exponent.|1|
|np.trunc(x, /[, out, where, casting, order, …])|Return the truncated value of the input, element-wise.|1|
|np.copysign(x1, x2, /[, out, where, casting, …])|Change the sign of x1 to that of x2, element-wise.|2|
|np.nextafter(x1, x2, /[, out, where, casting, …])|Return the next floating-point value after x1 towards x2, element-wise.|2|
|np.ldexp(x1, x2, /[, out, where, casting, …])|Returns x1 * 2**x2, element-wise.|2|
|np.fmod(x1, x2, /[, out, where, casting, …])|Return the element-wise remainder of division.|2|
|np.floor(x, /[, out, where, casting, order, …])|Return the floor of the input, element-wise.|2|
|np.ceil(x, /[, out, where, casting, order, …])|Return the ceiling of the input, element-wise.|2|


#### 4.1.1.4 Comparison functions
---
Below is the list of comparison functions.

|ufunc|Description|Minimum no. of array|
|----------|--------------------|---------------------|
|np.greater(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 > x2) element-wise.|2|
|np.greater_equal(x1, x2, /[, out, where, …])|Return the truth value of (x1 >= x2) element-wise.|2|
|np.less(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 < x2) element-wise.|2|
|np.less_equal(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 =< x2) element-wise.|2|
|np.not_equal(x1, x2, /[, out, where, casting, …])|Return (x1 != x2) element-wise.|2|
|np.equal(x1, x2, /[, out, where, casting, …])|Return (x1 == x2) element-wise.|2|
|np.logical_and(x1, x2, /[, out, where, …])|Compute the truth value of x1 AND x2 element-wise.|2|
|np.logical_or(x1, x2, /[, out, where, casting, …])|Compute the truth value of x1 OR x2 element-wise.|2|
|np.logical_xor(x1, x2, /[, out, where, …])|Compute the truth value of x1 XOR x2, element-wise.|2|
|np.logical_not(x, /[, out, where, casting, …])|Compute the truth value of NOT x element-wise.|2|
|np.maximum(x1, x2, /[, out, where, casting, …])|Element-wise maximum of array elements.|2|
|np.minimum(x1, x2, /[, out, where, casting, …])|Element-wise minimum of array elements.|2|
|np.fmax(x1, x2, /[, out, where, casting, …])|Element-wise maximum of array elements.|2|
|np.fmin(x1, x2, /[, out, where, casting, …])|Element-wise minimum of array elements.|2|

**Warning:**

> Do not use the Python keywords `and` and `or` to combine logical array expressions. These keywords will test the truth value of the entire array (not element-by-element as you might expect). Use the bitwise operators `&` and `|` instead.

> The bit-wise operators `&` and `|` are the proper way to perform element-by-element array comparisons. Be sure you understand the operator precedence: `(a > 2) & (a < 5)` is the proper syntax because `a > 2 & a < 5` will result in an error due to the fact that `2 & a` is evaluated first.

> the behavior of `maximum(a, b)` is different than that of `max(a, b)`. As a ufunc, `maximum(a, b)` performs an element-by-element comparison of `a` and `b` and chooses each element of the result according to which element in the two arrays is larger. In contrast, `max(a, b)`` treats the objects `a` and `b` as a whole, looks at the (total) truth value of `a > b` and uses it to return either `a or b` (as a whole). A similar difference exists between `minimum(a, b)`` and `min(a, b)``.

# Reference

  1. [Scipy](https://docs.scipy.org/doc/numpy/reference/)
  2. [Donne Martin](https://github.com/donnemartin/data-science-ipython-notebooks#numpy)
  3. [Python Data Science handbook:  Jake VanderPlas](https://jakevdp.github.io/PythonDataScienceHandbook/)
  4. [Pandas Cookbook](https://pandas.pydata.org/pandas-docs/stable/user_guide/cookbook.html#cookbook)
  5. [10 Minutes to pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html#min)
  6. [Pandas in Jupyter - Quickstart and Useful Snippets](https://nikgrozev.com/2015/12/27/pandas-in-jupyter-quickstart-and-useful-snippets/)